/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentRegisterRouteImport } from './routes/student/register'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as StudentStudentProfileRouteImport } from './routes/_student/student.profile'
import { Route as StudentStudentNotificationsRouteImport } from './routes/_student/student.notifications'
import { Route as StudentStudentEarningsRouteImport } from './routes/_student/student.earnings'
import { Route as StudentStudentDashboardRouteImport } from './routes/_student/student.dashboard'
import { Route as StudentStudentBrowseRouteImport } from './routes/_student/student.browse'
import { Route as StudentStudentApplyRouteImport } from './routes/_student/student.apply'
import { Route as AdminAdminStudentsRouteImport } from './routes/_admin/admin.students'
import { Route as AdminAdminRequestsRouteImport } from './routes/_admin/admin.requests'
import { Route as AdminAdminLmsRouteImport } from './routes/_admin/admin.lms'
import { Route as AdminAdminFeedbackRouteImport } from './routes/_admin/admin.feedback'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'
import { Route as AdminAdminCertificatesRouteImport } from './routes/_admin/admin.certificates'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/student/register',
  path: '/student/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LearnRoute,
} as any)
const StudentStudentProfileRoute = StudentStudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentNotificationsRoute =
  StudentStudentNotificationsRouteImport.update({
    id: '/student/notifications',
    path: '/student/notifications',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentStudentEarningsRoute = StudentStudentEarningsRouteImport.update({
  id: '/student/earnings',
  path: '/student/earnings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentBrowseRoute = StudentStudentBrowseRouteImport.update({
  id: '/student/browse',
  path: '/student/browse',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentApplyRoute = StudentStudentApplyRouteImport.update({
  id: '/student/apply',
  path: '/student/apply',
  getParentRoute: () => StudentRoute,
} as any)
const AdminAdminStudentsRoute = AdminAdminStudentsRouteImport.update({
  id: '/admin/students',
  path: '/admin/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminRequestsRoute = AdminAdminRequestsRouteImport.update({
  id: '/admin/requests',
  path: '/admin/requests',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminLmsRoute = AdminAdminLmsRouteImport.update({
  id: '/admin/lms',
  path: '/admin/lms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminFeedbackRoute = AdminAdminFeedbackRouteImport.update({
  id: '/admin/feedback',
  path: '/admin/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminCertificatesRoute = AdminAdminCertificatesRouteImport.update({
  id: '/admin/certificates',
  path: '/admin/certificates',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/admin/certificates': typeof AdminAdminCertificatesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/feedback': typeof AdminAdminFeedbackRoute
  '/admin/lms': typeof AdminAdminLmsRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/student/apply': typeof StudentStudentApplyRoute
  '/student/browse': typeof StudentStudentBrowseRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/earnings': typeof StudentStudentEarningsRoute
  '/student/notifications': typeof StudentStudentNotificationsRoute
  '/student/profile': typeof StudentStudentProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/admin/certificates': typeof AdminAdminCertificatesRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/feedback': typeof AdminAdminFeedbackRoute
  '/admin/lms': typeof AdminAdminLmsRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/admin/students': typeof AdminAdminStudentsRoute
  '/student/apply': typeof StudentStudentApplyRoute
  '/student/browse': typeof StudentStudentBrowseRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/earnings': typeof StudentStudentEarningsRoute
  '/student/notifications': typeof StudentStudentNotificationsRoute
  '/student/profile': typeof StudentStudentProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/impact': typeof ImpactRoute
  '/learn': typeof LearnRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/_admin/admin/certificates': typeof AdminAdminCertificatesRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/feedback': typeof AdminAdminFeedbackRoute
  '/_admin/admin/lms': typeof AdminAdminLmsRoute
  '/_admin/admin/requests': typeof AdminAdminRequestsRoute
  '/_admin/admin/students': typeof AdminAdminStudentsRoute
  '/_student/student/apply': typeof StudentStudentApplyRoute
  '/_student/student/browse': typeof StudentStudentBrowseRoute
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute
  '/_student/student/earnings': typeof StudentStudentEarningsRoute
  '/_student/student/notifications': typeof StudentStudentNotificationsRoute
  '/_student/student/profile': typeof StudentStudentProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/departments'
    | '/impact'
    | '/learn'
    | '/programs'
    | '/support'
    | '/learn/$slug'
    | '/student/login'
    | '/student/register'
    | '/admin/certificates'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/lms'
    | '/admin/requests'
    | '/admin/students'
    | '/student/apply'
    | '/student/browse'
    | '/student/dashboard'
    | '/student/earnings'
    | '/student/notifications'
    | '/student/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/departments'
    | '/impact'
    | '/learn'
    | '/programs'
    | '/support'
    | '/learn/$slug'
    | '/student/login'
    | '/student/register'
    | '/admin/certificates'
    | '/admin/dashboard'
    | '/admin/feedback'
    | '/admin/lms'
    | '/admin/requests'
    | '/admin/students'
    | '/student/apply'
    | '/student/browse'
    | '/student/dashboard'
    | '/student/earnings'
    | '/student/notifications'
    | '/student/profile'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_student'
    | '/about'
    | '/blog'
    | '/contact'
    | '/departments'
    | '/impact'
    | '/learn'
    | '/programs'
    | '/support'
    | '/learn/$slug'
    | '/student/login'
    | '/student/register'
    | '/_admin/admin/certificates'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/feedback'
    | '/_admin/admin/lms'
    | '/_admin/admin/requests'
    | '/_admin/admin/students'
    | '/_student/student/apply'
    | '/_student/student/browse'
    | '/_student/student/dashboard'
    | '/_student/student/earnings'
    | '/_student/student/notifications'
    | '/_student/student/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  ImpactRoute: typeof ImpactRoute
  LearnRoute: typeof LearnRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
  SupportRoute: typeof SupportRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/register': {
      id: '/student/register'
      path: '/student/register'
      fullPath: '/student/register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof LearnRoute
    }
    '/_student/student/profile': {
      id: '/_student/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentStudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/notifications': {
      id: '/_student/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentStudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/earnings': {
      id: '/_student/student/earnings'
      path: '/student/earnings'
      fullPath: '/student/earnings'
      preLoaderRoute: typeof StudentStudentEarningsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentStudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/browse': {
      id: '/_student/student/browse'
      path: '/student/browse'
      fullPath: '/student/browse'
      preLoaderRoute: typeof StudentStudentBrowseRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/apply': {
      id: '/_student/student/apply'
      path: '/student/apply'
      fullPath: '/student/apply'
      preLoaderRoute: typeof StudentStudentApplyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_admin/admin/students': {
      id: '/_admin/admin/students'
      path: '/admin/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminAdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/requests': {
      id: '/_admin/admin/requests'
      path: '/admin/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminAdminRequestsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/lms': {
      id: '/_admin/admin/lms'
      path: '/admin/lms'
      fullPath: '/admin/lms'
      preLoaderRoute: typeof AdminAdminLmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/feedback': {
      id: '/_admin/admin/feedback'
      path: '/admin/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminAdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/certificates': {
      id: '/_admin/admin/certificates'
      path: '/admin/certificates'
      fullPath: '/admin/certificates'
      preLoaderRoute: typeof AdminAdminCertificatesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminCertificatesRoute: typeof AdminAdminCertificatesRoute
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminFeedbackRoute: typeof AdminAdminFeedbackRoute
  AdminAdminLmsRoute: typeof AdminAdminLmsRoute
  AdminAdminRequestsRoute: typeof AdminAdminRequestsRoute
  AdminAdminStudentsRoute: typeof AdminAdminStudentsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminCertificatesRoute: AdminAdminCertificatesRoute,
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminFeedbackRoute: AdminAdminFeedbackRoute,
  AdminAdminLmsRoute: AdminAdminLmsRoute,
  AdminAdminRequestsRoute: AdminAdminRequestsRoute,
  AdminAdminStudentsRoute: AdminAdminStudentsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentRouteChildren {
  StudentStudentApplyRoute: typeof StudentStudentApplyRoute
  StudentStudentBrowseRoute: typeof StudentStudentBrowseRoute
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute
  StudentStudentEarningsRoute: typeof StudentStudentEarningsRoute
  StudentStudentNotificationsRoute: typeof StudentStudentNotificationsRoute
  StudentStudentProfileRoute: typeof StudentStudentProfileRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentApplyRoute: StudentStudentApplyRoute,
  StudentStudentBrowseRoute: StudentStudentBrowseRoute,
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
  StudentStudentEarningsRoute: StudentStudentEarningsRoute,
  StudentStudentNotificationsRoute: StudentStudentNotificationsRoute,
  StudentStudentProfileRoute: StudentStudentProfileRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface LearnRouteChildren {
  LearnSlugRoute: typeof LearnSlugRoute
}

const LearnRouteChildren: LearnRouteChildren = {
  LearnSlugRoute: LearnSlugRoute,
}

const LearnRouteWithChildren = LearnRoute._addFileChildren(LearnRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  ImpactRoute: ImpactRoute,
  LearnRoute: LearnRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
  SupportRoute: SupportRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentRegisterRoute: StudentRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
