/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentRegisterRouteImport } from './routes/student/register'
import { Route as StudentLoginRouteImport } from './routes/student/login'
import { Route as StudentStudentProfileRouteImport } from './routes/_student/student.profile'
import { Route as StudentStudentNotificationsRouteImport } from './routes/_student/student.notifications'
import { Route as StudentStudentEarningsRouteImport } from './routes/_student/student.earnings'
import { Route as StudentStudentDashboardRouteImport } from './routes/_student/student.dashboard'
import { Route as StudentStudentBrowseRouteImport } from './routes/_student/student.browse'
import { Route as StudentStudentApplyRouteImport } from './routes/_student/student.apply'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegisterRoute = StudentRegisterRouteImport.update({
  id: '/student/register',
  path: '/student/register',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentLoginRoute = StudentLoginRouteImport.update({
  id: '/student/login',
  path: '/student/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentStudentProfileRoute = StudentStudentProfileRouteImport.update({
  id: '/student/profile',
  path: '/student/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentNotificationsRoute =
  StudentStudentNotificationsRouteImport.update({
    id: '/student/notifications',
    path: '/student/notifications',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentStudentEarningsRoute = StudentStudentEarningsRouteImport.update({
  id: '/student/earnings',
  path: '/student/earnings',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentDashboardRoute = StudentStudentDashboardRouteImport.update({
  id: '/student/dashboard',
  path: '/student/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentBrowseRoute = StudentStudentBrowseRouteImport.update({
  id: '/student/browse',
  path: '/student/browse',
  getParentRoute: () => StudentRoute,
} as any)
const StudentStudentApplyRoute = StudentStudentApplyRouteImport.update({
  id: '/student/apply',
  path: '/student/apply',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/apply': typeof StudentStudentApplyRoute
  '/student/browse': typeof StudentStudentBrowseRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/earnings': typeof StudentStudentEarningsRoute
  '/student/notifications': typeof StudentStudentNotificationsRoute
  '/student/profile': typeof StudentStudentProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/student/apply': typeof StudentStudentApplyRoute
  '/student/browse': typeof StudentStudentBrowseRoute
  '/student/dashboard': typeof StudentStudentDashboardRoute
  '/student/earnings': typeof StudentStudentEarningsRoute
  '/student/notifications': typeof StudentStudentNotificationsRoute
  '/student/profile': typeof StudentStudentProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_student': typeof StudentRouteWithChildren
  '/about': typeof AboutRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/departments': typeof DepartmentsRoute
  '/programs': typeof ProgramsRoute
  '/support': typeof SupportRoute
  '/student/login': typeof StudentLoginRoute
  '/student/register': typeof StudentRegisterRoute
  '/_student/student/apply': typeof StudentStudentApplyRoute
  '/_student/student/browse': typeof StudentStudentBrowseRoute
  '/_student/student/dashboard': typeof StudentStudentDashboardRoute
  '/_student/student/earnings': typeof StudentStudentEarningsRoute
  '/_student/student/notifications': typeof StudentStudentNotificationsRoute
  '/_student/student/profile': typeof StudentStudentProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/departments'
    | '/programs'
    | '/support'
    | '/student/login'
    | '/student/register'
    | '/student/apply'
    | '/student/browse'
    | '/student/dashboard'
    | '/student/earnings'
    | '/student/notifications'
    | '/student/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/departments'
    | '/programs'
    | '/support'
    | '/student/login'
    | '/student/register'
    | '/student/apply'
    | '/student/browse'
    | '/student/dashboard'
    | '/student/earnings'
    | '/student/notifications'
    | '/student/profile'
  id:
    | '__root__'
    | '/'
    | '/_student'
    | '/about'
    | '/blog'
    | '/contact'
    | '/departments'
    | '/programs'
    | '/support'
    | '/student/login'
    | '/student/register'
    | '/_student/student/apply'
    | '/_student/student/browse'
    | '/_student/student/dashboard'
    | '/_student/student/earnings'
    | '/_student/student/notifications'
    | '/_student/student/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentRoute: typeof StudentRouteWithChildren
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DepartmentsRoute: typeof DepartmentsRoute
  ProgramsRoute: typeof ProgramsRoute
  SupportRoute: typeof SupportRoute
  StudentLoginRoute: typeof StudentLoginRoute
  StudentRegisterRoute: typeof StudentRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/register': {
      id: '/student/register'
      path: '/student/register'
      fullPath: '/student/register'
      preLoaderRoute: typeof StudentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/login': {
      id: '/student/login'
      path: '/student/login'
      fullPath: '/student/login'
      preLoaderRoute: typeof StudentLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/student/profile': {
      id: '/_student/student/profile'
      path: '/student/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentStudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/notifications': {
      id: '/_student/student/notifications'
      path: '/student/notifications'
      fullPath: '/student/notifications'
      preLoaderRoute: typeof StudentStudentNotificationsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/earnings': {
      id: '/_student/student/earnings'
      path: '/student/earnings'
      fullPath: '/student/earnings'
      preLoaderRoute: typeof StudentStudentEarningsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/dashboard': {
      id: '/_student/student/dashboard'
      path: '/student/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentStudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/browse': {
      id: '/_student/student/browse'
      path: '/student/browse'
      fullPath: '/student/browse'
      preLoaderRoute: typeof StudentStudentBrowseRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/student/apply': {
      id: '/_student/student/apply'
      path: '/student/apply'
      fullPath: '/student/apply'
      preLoaderRoute: typeof StudentStudentApplyRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface StudentRouteChildren {
  StudentStudentApplyRoute: typeof StudentStudentApplyRoute
  StudentStudentBrowseRoute: typeof StudentStudentBrowseRoute
  StudentStudentDashboardRoute: typeof StudentStudentDashboardRoute
  StudentStudentEarningsRoute: typeof StudentStudentEarningsRoute
  StudentStudentNotificationsRoute: typeof StudentStudentNotificationsRoute
  StudentStudentProfileRoute: typeof StudentStudentProfileRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentStudentApplyRoute: StudentStudentApplyRoute,
  StudentStudentBrowseRoute: StudentStudentBrowseRoute,
  StudentStudentDashboardRoute: StudentStudentDashboardRoute,
  StudentStudentEarningsRoute: StudentStudentEarningsRoute,
  StudentStudentNotificationsRoute: StudentStudentNotificationsRoute,
  StudentStudentProfileRoute: StudentStudentProfileRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentRoute: StudentRouteWithChildren,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DepartmentsRoute: DepartmentsRoute,
  ProgramsRoute: ProgramsRoute,
  SupportRoute: SupportRoute,
  StudentLoginRoute: StudentLoginRoute,
  StudentRegisterRoute: StudentRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
